---
background:
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunA_0.h5'
   name: '2023 ZB Run A'
   use: False
 - path: 
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunB_0.h5'
   name: '2023 ZB Run B'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunC_0.h5'
   name: '2023 ZB Run C'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunD_0.h5'
   name: '2023 ZB Run D'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_0.h5'
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_1.h5'
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_2.h5' 
   name: '2023 EZB Run C'
   use: True

signal:
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/SUEP.h5'
   name: 'SUEP'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/H_ToLongLived.h5'
   name: 'HtoLongLived'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/VBFHto2C.h5'
   name: 'VBHFto2C'
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/TT.h5'
   name: 'TT' 
   use: True
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/SUSYGGBBH.h5'
   name: 'SUSYGGBBH'
   use: True

exposure:
 training:
  - '/eos/project/c/cicada-project/data/2023/Signal/DummyOutliers-Training.h5'
 validation:
  - '/eos/project/c/cicada-project/data/2023/Signal/DummyOutliers-Validation.h5'
